### ISSUE TITLE
Edit text error in docs Javascript section

### ISSUE THREAD

**Issue by ChristinaRookie** [electricbookworks/electric-book#167]
It says 'Printing and ebooks is simpler without it, and it can quickly bloat websites. ' which sounds bad. Edit at least to 'Printing and ebooks are simpler without it, and it can quickly bloat websites. '

**Comment by arthurattwell** [comment]
Thanks @ChristinaRookie. Actually that whole section was out of date. Rewritten in dd225dad338947640872ddb9a27e5b067560d224.
