### ISSUE TITLE
Don't use gem-based themes (for now)

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#24]
Electric Book default config sets `theme:`. Before Jekyll 3.2, I'd been using `theme:` as a custom config field to set which folder to fetch Sass from, so that I could switch between designs. At the time, the Jekyll team were planning to introduce themes, and I guessed (wrong) that a `theme:` setting in config would behave like this, defining the folder in which to find theme files -- like in Wordpress.

Jekyll 3.2 then took a different path, and introduced gem-based themes and used `theme:` as an official/reserved config key that tells Jekyll to fetch the theme as a gem.

So I rolled with this change by bundling Sass and some includes into a [gem](https://github.com/electricbookworks/electric-book-classic-theme). It was a bit of a pain, but I could see the potential value.

But there is a problem. Gems might contain dodgy stuff, so for security reasons GitHub Pages can't let people use any old gem as their theme. So, presumably while GitHub figures this out, GitHub Pages *only* supports the official Jekyll Minima theme. See [https://pages.github.com/themes/](pages.github.com/themes) for the most disappointing page on the Internet of Jekyll things:

![image](https://cloud.githubusercontent.com/assets/1053331/20037697/0dac3df8-a42e-11e6-9d45-a56b34c1ec4e.png)

Which means that if you set *any* other theme (e.g. `theme: electric-book-classic-theme`) in config, the site will not build on GitHub Pages.

I've looked around and have found no indication of when and whether GitHub Pages will begin supporting other themes.

So: I'm quitting gem-based themes for the time being and going back to including all theme-like code (`_sass`, `_includes`, `_layouts`, `assets`) in the Electric Book Jekyll template. This is for various reasons:

1. The lack of support for Jekyll theme gems on GitHub Pages. I really want the Electric Book workflow to work on GitHub Pages out of the box.
2. The inconvenience of developing gem-based themes. It's not just inconvenient for me (given how intricately connected the Electric Book template and themes are), but newcomers need to be able to find and tinker with theme code easily, and having this in a gem is not easy enough.
3. The [possibility](https://github.com/jekyll/jekyll/issues/5434) that, in future, gems will be able to contain an entire Jekyll template, at which point we could stick the entire Electric Book template in a theme, including default `_data/meta.yml` and configs, and this gem could then replace the template.
4. The fact that for book production (at Fire and Lion) we're doing just fine with one thorough, well-organised set of partials and includes (the Electric Book Classic theme, which will soon be replaced with the [Electric Book Elements](https://github.com/electricbookworks/electric-book-elements-theme) theme I'm working on), and we could just keep improving it, offering new config-like options to switch between design and even structural variations.

**Comment by arthurattwell** [comment]
Done with v0.5.0

**Comment by arthurattwell** [comment]
FWIW, it looks like GitHub Pages will support at least [one new theme](https://github.com/github/pages-gem/blob/master/lib/github-pages/dependencies.rb#L42-L45).

**Comment by ashmaroli** [comment]
and now, it supports *many* [more themes](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L43-L60) :smiley:
