### ISSUE TITLE
Image conversion with gulp not working on OSX

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#268]
When @DioneMentis and @ChristinaRookie process images with Gulp, the images that GraphicsMagick processes have an invalid colour profile attached. In a project with CMYK source images, this means the colours on screen look wrong (as CMYK colours do in an RGB environment, with garish greens in particular).

I can't replicate this on Windows or on Ubuntu, where I have no problems.

- On Windows 10, I'm using GraphicsMagick v1.3.26 installed from the official site.
- On Ubuntu 16.04, I'm using GraphicsMagick v 1.3.23 installed with `apt install graphicsmagick`.

I also tried installing the latest GraphicsMagick (v.1.3.29) on Ubuntu using the [official unzip-and-build instructions](http://www.graphicsmagick.org/INSTALL-unix.html), but the default config installs without JPEG support, and then our gulp script does not output images (I was testing with a JPEG image). And I couldn't figure out how to build-and-install with JPEG support on. The version that I get with `apt install graphicsmagick`, while older, does have JPEG support (and other features) enabled by default.

This makes me think we need to investigate feature support in the OSX version that @DioneMentis and @ChristinaRookie have installed. It may not ship with the features that we need enabled. I believe they have installed GraphicsMagick with Homebrew, which uses [this recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphicsmagick.rb).

It looks like that recipe might not enable [Little CMS](http://www.littlecms.com/) by default, which may be the library that handles colour profiles. Little CMS is enabled in my working versions of GraphicsMagick on Windows and Ubuntu.

@DioneMentis @ChristinaRookie If you type `gm version` in a Terminal, you should see output that looks something like this (this is what I get on Windows):

```                                
Feature Support:                
  Native Thread Safe       yes  
  Large Files (> 32 bit)   yes  
  Large Memory (> 32 bit)  yes  
  BZIP                     yes  
  DPS                      no   
  FlashPix                 no   
  FreeType                 yes  
  Ghostscript (Library)    no   
  JBIG                     yes  
  JPEG-2000                yes  
  JPEG                     yes  
  Little CMS               yes  
  Loadable Modules         yes  
  OpenMP                   yes (200203)
  PNG                      yes  
  TIFF                     yes  
  TRIO                     no   
  UMEM                     no   
  WebP                     yes  
  WMF                      yes  
  X11                      no   
  XML                      yes  
  ZLIB                     yes  
```

On your systems, what does it say for `Little CMS`?

**Comment by ChristinaRookie** [comment]
I have a whole lot more 'no's than you do @arthurattwell 

![screen shot 2018-05-21 at 10 50 48](https://user-images.githubusercontent.com/25814064/40298931-04034988-5ce5-11e8-985e-9ca6aff0092e.png)

**Comment by arthurattwell** [comment]
@ChristinaRookie and I have now established that the problem is indeed the missing Little CMS feature. So, when installing GraphicsMagick on OSX with Homebrew, you have to explicitly specify that you want it installed with Little CMS 2. To do this you install with this command in the Terminal:

```
brew install graphicsmagick --with-little-cms2
```

If you already have GraphicsMagick installed, you must first uninstall it with

```
brew uninstall graphicsmagick
```

before installing again with Little CMS 2.

**Comment by ChristinaRookie** [comment]
@arthurattwell the docs don't mention GraphicsMagick at all, should they?

**Comment by arthurattwell** [comment]
@ChristinaRookie Ah, yes, they should indeed. Perhaps as part of @DioneMentis's work on translation docs, we should update the docs from the ones currently on the template repo, without overwriting any CORE-specific docs (e.g. on definition includes, which aren't in the template). Do you think that's possible?

E.g. the latest EBT docs include sections on setting up your computer, which do mention GraphicsMagick.
