### ISSUE TITLE
Consider making Screen PDF the default for MS Word export conversion

### ISSUE THREAD

**Issue by ChristinaRookie** [electricbookworks/electric-book#360]
The current default for MS Word export conversion is Print PDF, however there are some image issues related to using Print PDF for this. The Screen PDF conversion is preferable, so we might want to make it the default.

cc @arthurattwell

**Comment by arthurattwell** [comment]
Good idea. Yes, the screen PDF output is far better largely because a Word file from the print-PDF version would contain big, print-quality images.
