### ISSUE TITLE
Inserting simple image fails for PDF and epub output

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#421]
I just cloned the electric-book repository and was trying out generating the "samples" book.  The samples book appears to be generated correctly, except for screen PDF, print PDF, and epub output the first image in the "Plain Images" chapter does not show up correctly.  Instead the output contains a raw XHTML string like "&lt;img src="../images/screen-pdf/naples.svg" class=" inject-svg" alt="A map of Naples https://en.wikipedia.org/wiki/Naples" /&gt;", followed by the caption.

The other images included in the "Count of Monte Cristo" section also show up as XHTML instead of the actual image. However, the figure 1 and figure 2 later in the chapter are inserted correctly in the PDF and epub output. In addition, all images in the chapter appear correctly when generating a web site.

Finally, when validating the epub output using epubcheck, it gives errors of the form "ERROR(RSC-005): samples.epub/text/02-01-plain-images.xhtml(28,11): Error while parsing file: element "noscript" not allowed here; expected the element end-tag, text, ..."

I have tried this on both Mac OS X and Ubuntu 18.04 LTS with the same result.  In both cases I followed the instructions on how to install the various dependences.  I then ran 'run-mac.command' (or 'run-linux.sh'), chose option 9 to update dependences, then option 7 to convert source images, and then one of options 1, 2, or 4 to generate the PDF or epub output.

Please let me know what further information you'd like me to provide to help troubleshoot this.

**Comment by arthurattwell** [comment]
@jaycolmvar Thank you! You've found a silly mistake that I made in #419. When adding lazy-loading of images, I didn't ensure that SVGs were being properly loaded in all formats. Sorry for costing you all that debugging time.

I've pushed a fix in https://github.com/electricbookworks/electric-book/pull/422.

**Comment by jaycolmvar** [comment]
Thanks for the quick response! Would this fix also apply to .jpg and .png image files?  The "Plain Images" chapter of the samples book has some .jpg images in the Count of Monte Cristo section, and I had the same problem with .png images in a test book I was doing.

**Comment by jaycolmvar** [comment]
Ignore my previous comment. I just checked out the fix-pdf-image-after-lazyloading branch and tested the samples book again. It looks good now in both PDF and epub, with the .jpg files loading fine.
