### ISSUE TITLE
Error in node_modules/kew/kew.js while converting images 

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#445]
I've previously successfully put images into book/images/_source and converted them for use using option 7, "Convert source images to output formats". However when I attempt to add a new image file right now, the conversion fails while creating a print-pdf image with an error

  .../node_modules/kew/kew.js:198
      throw e
      ^
TypeError: Cannot read property 'forEach' of null

The problem apparently arose after I did the "Install or update dependencies" operation (option 9); I have a separate installation on Ubuntu 18.04 where an older electric-book install works.

To test what might be going on, I tried reproducing the problem as follows:

1. I instantiated a brand-new VM on Digital Ocean running Ubuntu 18.04 LTS.
2. I used the ebw-usb-setup.sh shell script to install the EBW toolset from the EBW repository.
3. I got a new JPG file and put it in the book/images/_source subdirectory of the new-electric-book directory. (Because all the image files in the repository as cloned had already been converted.)
3. I ran run-linux.sh in the new-electric-book directory and did the "install or update dependencies" operation. It failed due to permissions problems, with access errors relating to files in ~/.npm/_cacache/index-v5/.
4. I changed ownership of all the files in ~/.npm to me and ran run-linux.sh again. This time the "install and update dependencies" operation appeared to succeed.
5. I ran option 7, "Convert source images to output formats" on the "book" subdirectory. It failed with the exact same error as above when attempting to convert the new JPG file.

I' d be glad to do further testing as needed, and in any case will probably try another clean install on Ubuntu to verify my prior experience. But right now my impression is that a clean install of the current EBW version will result in the error above when converting image files.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar, I'll see if I can replicate this as soon as I get a chance.

**Comment by arthurattwell** [comment]
Thanks again, @jaycolmvar, and my apologies for taking so long to get to this. You've found a bug that I introduced, [as explained in the fix I've just PRed here](https://github.com/electricbookworks/electric-book/pull/459).

**Comment by jaycolmvar** [comment]
My apologies for not thanking you earlier for fixing this -- I've been offline for a couple of weeks. Thanks again!
