### ISSUE TITLE
"Gem::ConfigMap is deprecated" warnings when running ebw-usb-setup.sh and run-linux.sh

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#465]
First, my apologies for filing more issues on things that are not necessarily core to the electric-book system. In my defense, I really like the electric-book way of doing things, am looking to use it for my own book, and want to make sure nothing hinders me in doing that. Now for the issue itself:

I am trying to work from a clean install of Ubuntu 18.04.4 LTS, and am installing dependencies by running the ebw-usb-setup.sh script without modifications. During the installation I get a series of warning messages as follows:

/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated

The same warnings are printed when running the run-linux.sh script and generating output (a screen PDF in my case).

I believe this is related to an existing rubygems issue <https://github.com/rubygems/rubygems/issues/3068>, apparently having to do with a conflict with the OS-provided ruby. The workaround suggested in that issue is to not use "gem update --system" on a system like Ubuntu with OS-provided ruby where you've already done "apt install ruby" (as the ebw-usb-setup.sh script does).

Short of getting a fix into rubygems and/or Debian/Ubuntu, I'm not sure how this issue gets resolved. People commenting in the rubygems issue have suggested instead doing "sudo gem update --system 3.0.6" (to get a rubygems version before the deprecation message was added?). I will try that with a modified ebw-usb-setup.sh script on another test run starting from scratch Ubuntu 18.94.4, but I don't know if that would cause problems elsewhere in the EB code.

**Comment by jaycolmvar** [comment]
OK, I did a second test, this time modifying one line of the ebw-usb-setup.sh script to read as follows:

sudo gem update --system 3.0.6 --no-ri --no-rdoc

instead of the original line without the "3.0.6". This eliminated the warning messages both on running ewb-usb-setup.sh and also in running run-linux.sh to generate screen PDF output. But as i wrote previously, I don't know if this will have any ill effects somewhere else.

**Comment by arthurattwell** [comment]
@jaycolmvar Thanks for this and for #466. Unfortunately my team and I aren't able to test and maintain that Ubuntu install script (as you say it's not part of our core workflow, it was originally created for a once-off prototype project using USB drives). So your improvements are much appreciated! If you haven't already, would you be willing to fork my gist, and make your improvements there? I can then update my gist accordingly?

**Comment by jaycolmvar** [comment]
Thanks for your response. Unfortunately, 1) I have never actually created a pull request on a git repository (I'm a relative newbie regarding git and Git/hub), and 2) after looking for info about how to do this, it looks as if it's not possible to create a pull request on a gist.

So... what I did was to fork your gist, clone the fork to my system, update with my changes, and commit them back to github. (In retrospect I should have created a git branch to do this, instead I just committed to master.) In any case, you can find my updated copy of ebw-usb-setup.sh at https://gist.github.com/jaycolmvar/ea4c9ac381c502023b5cc74eeeea168c

If I screwed this process up in some way please let me know and I will try to fix it.

**Comment by jaycolmvar** [comment]
One final comment as an FYI: I got ambitious and tried to install the electric-book framework on Ubuntu 20.04 LTS (mainly because that release has somewhat better Macintosh key mapping for folks like me running in a VM under macOS). I actually managed to get this to work, but running Jekyll with Ruby 2.7 (which is the default in Ubuntu 20.04) gives annoying warning messages relating to changed ways of handling positional and keyword arguments. The issue will be fixed in Jekyll 4.1, and I tried running the latest version of that from GitHub, but that breaks other stuff in electric-book framework. Also, xpdf is no longer shipped with Ubuntu 20.04, so you'd have to build it yourself.

So my general recommendation to people is to stick with Ubuntu 18.04 LTS for now.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar! That's perfect. Gists are a bit odd, as you've discovered: they are technically Git repos, but without the collaboration tools that GitHub provides for full repos. So I've manually merged your latest version into my original, which retains the history of your contribution here:

https://gist.github.com/arthurattwell/2684d50c286f3b005ea84eb61954458f/revisions

For interest, manually merging a forked gist into the original takes a few git commands that I've just written up [here](https://gist.github.com/arthurattwell/74593b4e1d32f42ad5b214803207b001).
