### ISSUE TITLE
"Unhandled rejection Error: EACCES: permission denied" when running ebw-usb-setup.sh

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#466]
Another error I saw when running ebw-usb-setup on a clean Ubuntu 18.04.4 install: multiple instances of the following (varying as to the exact directory):

Unhandled rejection Error: EACCES: permission denied, mkdir '/home/jaycolmvar/.npm/_cacache/index-v5/1b/b7'

This appears to be happening in the section "Install EB template dependencies", with the first error message occurring right after the output lines:

Bundle complete! 2 Gemfile dependencies, 25 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

I'm guessing that the errors are thus occurring during the command "npm install" run in the electric-book subdirectory, which is not run as root. However the (presumed) debug log for this command (~/.npm/_logs/2020-04-19T19_13_24_201Z-debug.log) does not show any permission errors. The debug log does though show an error "8025 error cb() never called!" at the very end, which I'm not sure is related.

Upon inspection the ~/.npm directory does contain a number of files and directories owned by root, all but one in ~/.npm/_cacache. Presumably those were created while running "sudo npm install" earlier, and should be owned by the user instead.

I don't know if these errors would end up causing other errors downstream, but just in case I'm going to do another test run from clean Ubuntu 18.04.4, adding the line 

sudo find ~/.npm -exec chown $USER.$USER {} \;

right before the "npm install".

**Comment by jaycolmvar** [comment]
OK, adding that line to the script helped, but there was still an error produced on the (non-sudo) "npm install", as follows:

npm update check failed                    │
│             Try running with sudo or get access              │
│             to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) /home/jaycolmvar/.config 

I'll try adding that line to the script as well and doing another test run. (And I'll change my original added line to use chown -R instead of "find -exec chown".

**Comment by arthurattwell** [comment]
@jaycolmvar Do your changes mentioned in https://github.com/electricbookworks/electric-book/issues/465 now solve this issue, as far as you can tell?

**Comment by jaycolmvar** [comment]
My apologies for the delays in responding. Yes, the changes I made to the script per #465 address this issue also. I can now do a clean installation of the EBW framework on Ubuntu 18.04 LTS.

**Comment by arthurattwell** [comment]
Thanks so much, @jaycolmvar, that's a huge help.
