### ISSUE TITLE
Gemfile now needs to include kramdown-parser-gfm

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#501]
I do periodic updates of my book's directory to match as closely as possible what is currently in EBW master. After making updates to match the current master (including the latest version of the EBW Gemfile), doing "bundle update" and "bundle install" to update the gems (I can never remember which I'm supposed to use, so do both), and doing "Install or update dependencies" in run-linux.sh, I got the following error when running run-linux.sh and trying to generate a screen PDF:

  Dependency Error: Yikes! It looks like you don't have kramdown-parser-gfm or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_docs/about/intro.md':
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm

This gem isn't referenced in the Gemfile, and neither is the kramdown gem itself; I presume it's pulled in when installing the jekyll gem.

In any case, I added the following line to Gemfile:

gem 'kramdown-parser-gfm'

and then did "bundle update" and "bundle install". This appears to resolve the problem, and I was able to successfully run run-linux.sh and generate a screen PDF.

According to <https://kramdown.gettalong.org/parser/gfm.html> the gem kramdown-parser-gfm was previously part of the main kramdown gem and is now split out separately. Apparently it's not pulled in as a dependency by anything else, even though it appears to be used by EBW under the covers.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar. We hit this issue too, and discovered quite the rabbit hole. I've made some changes in https://github.com/electricbookworks/electric-book/pull/509 where I've also written up the related issues as I understand them.

If the changes there don't fix it for you (if and when you try), feel free to reopen this issue.

**Comment by jaycolmvar** [comment]
Thanks for looking at this. I am currently building successfully with the one change I described (adding kramdown-parser-gfm). I do *not* use Github Pages, and do not plan to. Right now I'm just generating screen PDF, epub (which validates without issues using epubcheck 4.2.4), and web (which, if I use it, will end up on a domain and web server that I control).

I like to keep up with your releases, and will try updating to the latest EB files to see if I have any issues. But I'm working in a VM, so I'll snapshot it before I do this in case I need to roll back and stay on what I have. I'll let you know how it goes.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar!

**Comment by jaycolmvar** [comment]
I updated my EBT files to the current latest: did a git clone into a separate directory, compared all the files from that to what I have, and copied over what differed (except for a few files like _data/meta.yml where I made local changes). I used the unmodified EBT Gemfile as updated to use the GitHub Pages gem. Then I did  "Install or update dependencies" in run-linux.sh.

Screen PDF, epub, and web version all build cleanly with no errors, and appear to be clean when I look at them. So I'm going to stay on the new EBT files going forward.

P.S. I did get a fatal error when trying to build a search index for the web version, but that may have existed before--I've never tried to do that. I'll file a separate issue about that. You can leave this issue closed.
