### ISSUE TITLE
Inline (emphasis) sidenote leaves spaces

### ISSUE THREAD

**Issue by tgraham-antenna** [electricbookworks/electric-book#595]
The sidenote in the sample beginning with "Reviewed in Sz Horvát" leaves a space in the body text so that the body text contains "in any size of brain* . The".  There should not be a space in "* .".

See https://electricbookworks.github.io/electric-book/samples/text/01-07-notes.html#notes

**Comment by arthurattwell** [comment]
Fixed in 8250c51c611bf3a4b9fd460f2925bc7c6841892f.
