### ISSUE TITLE
"unknown page region '@right-center'" with _print-page-setup-lightning-source.scss

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#631]
I'm finishing up my book and am trying to squash a few remaining bugs. This is one of them, and fortunately has an easy fix.

Briefly, I've set `$print-page-setup-lightning-source` to "true" in `book/styles/print-pdf.scss` in order to get print-pdf output that I think will pass muster with Amazon KDP print-on-demand. However, this causes the following warning messages when generating print-pdf output:

    prince: ../styles/print-pdf.css:1: warning: unknown page region '@right-center'
    prince: ../styles/print-pdf.css:1: warning: unknown page region '@left-center'

This message is apparently caused by two lines in `_sass/template/partials/_print-page-setup-lightning-source.scss` that use `@right-center` and `@left-center` to refer to particular page regions.

After reading the Prince XML online documentation, I've concluded that those references should instead be to `@right-middle` and `@left-middle`. (I suspect the "-center" suffix works only for "@top-center" and "@bottom-center".)

Sure enough, after making that change to `_print-page-setup-lightning-source.scss` the warning message goes away.

**Comment by arthurattwell** [comment]
Housekeeping unattended issues. Thank you, @jaycolmvar!

This issue was resolved by https://github.com/electricbookworks/electric-book/commit/fe5c0e9e7fe2e4170d8a8cd2bfdf9f23a187a9be.
