### ISSUE TITLE
New YAML file for translatable interface labels

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#90]
Further to a separate conversation with @SteveBarnett, I think we should create a new YAML file in `_data` for translatable web-interface elements. At the moment, we have a couple of these in `meta.yml`, such as `nav-label` and `home-label`. But `meta` refers to book metadata, and this file should really contain only that. That is, `meta.yml` might, in theory, travel with the book content outside of Jekyll. Site interface terms/labels are specific to the website, not the book content it presents, so they should be stored separately. 

Moreover, unlike book metadata, these site terms would be translated should the site be translated. We might even, someday, be able to generate a site in more than one language at a different baseurl (e.g. `example.com/fr`) by drawing on new site-term files, allowing users to switch between languages.

There are already conventions ([e.g. for Wordpress](https://developer.wordpress.org/plugins/internationalization/localization/)) for what these kinds of lists of localising terms are called, and we could name our YAML file to match those conventions. We will also need to think about whether we do all localisation in one file or in some kind of folder structure. We don't have a lot to translate, so my initial sense is that we should use one file that lists variables and then, for each variable, terms as `language: "Phrase"` hashes, e.g.

```
home-label:
  en: "Home"
  fr: "Page d'accueil"
```

Adding this file would bring to four the number of places we store variable values:

1. `config.yml` for variables that make the machine work
2. `meta.yml` for book metadata
3. each of our four output formats' master `scss` files, for appearance-related variables
4. this new site-terms file, for localised website terms.

To guard against an ever increasing list, are there any other kinds of variables we need to be storing, or is this about it?

**Comment by SteveBarnett** [comment]
For translations specifically: I think that POT files are the standard way to do it, so we should follow that and have separate files for each language. It's okay if they are tiny :).

Re bring to four the number of places: that does feel a little scary, but as long as the places are clear I think it's okay.

The `meta.yml` is getting pretty huge now and it would be worth chatting about if we can make that more modular.

**Comment by SteveBarnett** [comment]
@arthurattwell Looooong, great, article on Jekyll [here](https://mademistakes.com/articles/using-jekyll-2016/), with [a bit about translations](https://mademistakes.com/articles/using-jekyll-2016/#translation-keys) in a `languages.yml`.

**Comment by arthurattwell** [comment]
Deon in #209
